#!/usr/bin/env python3
import requests
import re

# what is ct and ck? 
# these are tokens generated by the router login logic, rewriting it turned out to be too complicated
# therefore, you have to view them yourself in the console of your browser when logging into the router
# search for POST request at address login.cgi
# the following tokens were generated for the default values for the router from the operator inea - user:ineagpon

url = "192.168.1.1"
ct = "2Awp6Rntn24AtFDkwCioWarQFk734lYGf0lIz6EoJdv1E741j-_mChCqgJzmSby4OvHDpyTcIs87PeKeKxkEpRS7vYEoLFX3_LhVuF4fWE9SP8pfhR8I-jsynfwfpGDWqX5mXBClQgnjudj0_evkf0UJZYCaiZgmEI3G8OwV5BqP5nDreYL1RmS_9xNgfjdMu6LTALtiCqrg_0yi-XF4Kr8HAsK0UvDXugmk8nNoi8eDWk_ELGVwDcuJtxsRgbzN8yJXvqJD_Iqnf_A1G7yq7T9vLRCYb5loHljS5GGC7dI"
ck = "mqdh47u9tZ4pMNyMkK5bSOvEdN8XgeRwplu24qLG7fwDPRcxNPQMy0HVbp0sXb7cSqe6EUoEMIHt1btDghNp16AogCS531fNeBqT4Vt1bVnONu6cIash2yvjOCZtInruarFsuerxsxv8K7-80cYTvQKgdsqSUH2CZ0BSGH_D7yQ."

def restart():
    print("Trying to login to router")

    loginUrl = 'http://' + url + '/login.cgi'
    loginBody = {
        'encrypted': '1',
        'ct': ct,
        'ck': ck
    }

    try:
        response = requests.post(loginUrl, data = loginBody)
        print("Login response code " + str(response.status_code))
    except:
        print("Error login to system")

    setCookieHeader = response.headers['Set-Cookie']
    sid = re.search('sid=([a-zA-Z]+);', setCookieHeader, re.IGNORECASE).group(1)
    lsid = re.search('lsid=([a-zA-Z]+);', setCookieHeader, re.IGNORECASE).group(1)

    print("Trying to get csrf_token")

    getCsrfUrl = 'http://' + url + '/device_status.cgi'
    getCsrfHeaders = {
        'Cookie': 'lang=eng; sid=' + sid + '; lsid=' + lsid,
    }

    try:
        response = requests.get(getCsrfUrl, headers = getCsrfHeaders)
        print("Get csrf_token response code " + str(response.status_code))
    except:
        print("Error getting csrf_token to system")

    csrf_token = re.search('csrf_token=([a-zA-Z]+)', response.content.decode("utf-8"), re.MULTILINE).group(1)

    print("Trying to restart router")

    restartUrl = 'http://' + url + '/reboot.cgi?reboot'
    restartRawData = 'data&csrf_token=' + csrf_token
    restartHeaders = {
        'Cookie': 'lang=eng; sid=' + sid + '; lsid=' + lsid,
        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
    }

    try:
        response = requests.post(restartUrl, data = restartRawData, headers = restartHeaders)
        print("Restart response code " + str(response.status_code))
    except:
        print("Error restarting router")

try:
    restart()
except Exception as e:
    print(str(e))